version: "2.1"

jobs:
  nix-build:
    docker:
      - image: "nixos/nix:2.13.2"

    environment:
      # Let us use features marked "experimental".  For example, most/all of
      # the `nix <subcommand>` forms.
      NIX_CONFIG: "experimental-features = nix-command flakes"

    steps:
      - "checkout"
      - run:
          name: "nix build"
          command: |
            nix build

workflows:
  ci:
    jobs:
      - nix-build
